// A hooks module and its tests import only files inside the plugin, so this copies in the board's rules and the demo specs.

import { build } from 'esbuild';
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const here = fileURLToPath(new URL('.', import.meta.url));
const repo = join(here, '..', '..');

await build({
    entryPoints: [join(repo, 'apps', 'copilot-canvas', 'spec-rules.mjs')],
    bundle: true,
    absWorkingDir: repo,
    format: 'esm',
    platform: 'neutral',
    target: 'es2022',
    outfile: join(here, 'hooks', 'vendor', 'board-rules.mjs'),
    banner: { js: '// Generated by apps/claude-mod/build.mjs from apps/copilot-canvas/spec-rules.mjs. Do not edit.' },
    logLevel: 'warning',
});

// The fixtures as staged in git, never the working copies the viewer mutates when you click through it.
const git = args => execFileSync('git', args, { cwd: repo, encoding: 'utf8', maxBuffer: 1 << 24 });
const fixtures = {};
for (const path of git(['ls-files', '--', 'specs/_0*_demo-*']).split('\n').filter(p => /^specs\/_0\d_demo-[^/]+\/[^/]+$/.test(p)).sort()) {
    fixtures[path] = git(['show', `:${path}`]);
}
writeFileSync(
    join(here, 'tests', 'fixtures', 'demo-specs.js'),
    '// Generated by apps/claude-mod/build.mjs from specs/_0N_demo-*. Do not edit.\n'
        + `export const DEMO_SPECS = ${JSON.stringify(fixtures, null, 2)}\n`,
);

console.log(`built hooks/vendor/board-rules.mjs and tests/fixtures/demo-specs.js (${Object.keys(fixtures).length} files)`);
