// Takes the Copilot app board's pictures into the shots library: light theme, twice the pixel density, headless.
// usage: node tooling/scripts/board-shots.mjs [--out <dir>]
import { mkdtempSync, mkdirSync, cpSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright-core';
import { createSpecServer } from '../../apps/copilot-canvas/server.mjs';

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const at = process.argv.indexOf('--out');
const OUT = resolve(REPO, at > -1 ? process.argv[at + 1] : '.shots');
mkdirSync(OUT, { recursive: true });
const TEAMBOARD = join(REPO, 'apps/vscode/webview/src/spec-viewer/__fixtures__/teamboard/041-profile-photo-upload');
const root = join(mkdtempSync(join(tmpdir(), 'canvas-page-')), 'teamboard'); mkdirSync(root);
mkdirSync(join(root, 'specs'));
for (const demo of ['_00_demo-specified', '_01_demo-planned', '_02_demo-tasked', '_03_demo-living']) cpSync(join(REPO, 'specs', demo), join(root, 'specs', demo), { recursive: true });
const rich = join(root, 'specs', '041-profile-photo-upload');
mkdirSync(join(rich, 'checklists'), { recursive: true });
for (const name of ['spec.md', 'plan.md', 'tasks.md', 'research.md', 'data-model.md']) cpSync(join(TEAMBOARD, name), join(rich, name));
cpSync(join(TEAMBOARD, 'spec-context.completed.json'), join(rich, '.spec-context.json'));
mkdirSync(join(root, '.specify/extensions/companion'), { recursive: true });
const board = await createSpecServer({ root, send: async () => true });
const browser = await chromium.launch({ headless: true, channel: 'chrome' });
const opts = { viewport: { width: 1180, height: 760 }, deviceScaleFactor: 2, colorScheme: 'light' };
const page = await browser.newPage(opts);
await page.goto(board.url);
await page.waitForSelector('.spec-card');
await page.waitForFunction(() => document.body.classList.contains('vscode-light'));
const shot = (p, name, clip) => p.screenshot({ path: join(OUT, name + '.png'), ...(clip ? { clip } : {}) });
const toastShown = (p) => p.waitForFunction(() => getComputedStyle(document.getElementById('toast')).opacity === '1');
await page.click('[data-filter="all"]');
await page.click('.spec-card[data-id="specs/_02_demo-tasked"]');
await page.waitForSelector('.next');
await shot(page, 'board', {x:0,y:0,width:1180,height:664});
await page.click('.spec-card[data-id="specs/_01_demo-planned"]');
await page.waitForSelector('.next-title:has-text("Next: Tasks")');
await shot(page, 'board-next-step', {x:360,y:57,width:820,height:400});
await page.click('.next .btn-primary');
await page.waitForSelector('.toast.is-visible');
await page.waitForSelector('.next .btn-primary:not(:disabled)');
await toastShown(page);
await shot(page, 'board-sent');
await page.click('#toast-actions button:has-text("Show prompt")');
await page.waitForTimeout(400);
await shot(page, 'board-sent-prompt', {x:300,y:240,width:880,height:520});
await page.click('#toast-actions [aria-label="Dismiss"]');
await page.click('#new-spec-toggle');
await page.fill('#new-spec-text', 'Show a footer count');
await page.waitForTimeout(300);
await shot(page, 'board-new-spec');

const stockRoot = join(mkdtempSync(join(tmpdir(), 'canvas-page-stock-')), 'todo-app');
mkdirSync(join(stockRoot, 'specs'), { recursive: true });
cpSync(join(REPO, 'specs', '_01_demo-planned'), join(stockRoot, 'specs', '_01_demo-planned'), { recursive: true });
const stock = await createSpecServer({ root: stockRoot, send: async () => true });
const sp = await browser.newPage(opts);
await sp.goto(stock.url);
await sp.waitForSelector('.next');
await sp.waitForFunction(() => document.body.classList.contains('vscode-light'));
await shot(sp, 'board-stock');
await sp.locator('.next .install-hint .btn-link').click();
await sp.waitForTimeout(300);
await shot(sp, 'board-install-hint', {x:360,y:57,width:820,height:470});
await sp.click('#new-spec-toggle');
await sp.waitForTimeout(300);
await shot(sp, 'board-stock-new-spec');
await browser.close(); await board.close(); await stock.close();
console.log(`Board pictures written to ${OUT}`);
process.exit(0);
