#!/usr/bin/env node
// Puts the terminal player and one terminal script's frames into a HyperFrames project, as files the composition loads with plain script tags.
// usage: node tooling/video/terminal-player/build.mjs <project-dir> [--frames <capture-dir>] [--script terminal-script.json]
import { cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, '..', '..', '..');
const arg = (name, fallback) => {
    const at = process.argv.indexOf(`--${name}`);
    return at > -1 ? process.argv[at + 1] : fallback;
};
const project = resolve(process.argv[2] ?? '.');
const scriptFile = join(project, arg('script', 'terminal-script.json'));
if (!existsSync(scriptFile)) {
    console.error(`[terminal-player] Missing terminal script at ${scriptFile}`);
    process.exit(2);
}
const script = JSON.parse(readFileSync(scriptFile, 'utf8'));
const captures = resolve(arg('frames', join(REPO, '.terminal-check', script.captures ?? '')));
const kept = join(project, 'assets', 'terminal', 'frames');
mkdirSync(kept, { recursive: true });
const names = [...new Set([script.start, ...script.beats.filter(beat => beat.do === 'frame').map(beat => beat.to)])];
const frames = {};
for (const name of names) {
    const fresh = join(captures, `${name}.grid.json`);
    // A frame already kept in the project is used as it is when no capture folder has a newer one.
    if (existsSync(fresh)) cpSync(fresh, join(kept, `${name}.grid.json`));
    if (!existsSync(join(kept, `${name}.grid.json`))) {
        console.error(`[terminal-player] Missing frame "${name}": not in ${captures} and not kept in the project`);
        process.exit(2);
    }
    frames[name] = JSON.parse(readFileSync(join(kept, `${name}.grid.json`), 'utf8'));
}
for (const file of ['player.js', 'player.css']) cpSync(join(HERE, file), join(project, 'assets', 'terminal', file));
writeFileSync(join(project, 'assets', 'terminal', 'data.js'), `// Generated by tooling/video/terminal-player/build.mjs from terminal-script.json and its frames. Do not edit.\nwindow.TERMINAL = ${JSON.stringify({ script, frames })};\n`);
console.log(`${names.length} frames and the player written to ${join(project, 'assets', 'terminal')}`);
