// Bundles the VS Code spec viewer's markdown renderer, stylesheet and step timing, and the prompt preamble, into vendor/, so the board
// renders spec, plan and tasks exactly the way the extension does. Run: node apps/copilot-canvas/build.mjs

import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const here = fileURLToPath(new URL('.', import.meta.url));
const webview = join(here, '..', 'vscode', 'webview');
// esbuild writes source paths into the bundle as comments, relative to its working dir: pin it so the output does not depend on where this runs.
const absWorkingDir = join(here, '..', '..');

// The renderer's only webview dependency is a Preact signal it reads for living-spec coverage; the board has none.
const stubSignals = {
    name: 'stub-signals',
    setup(api) {
        api.onResolve({ filter: /^\.\.\/signals$/ }, () => ({ path: 'signals-stub', namespace: 'stub' }));
        api.onLoad({ filter: /.*/, namespace: 'stub' }, () => ({ contents: 'export const navState = { value: null };', loader: 'js' }));
    },
};

await build({
    entryPoints: [join(webview, 'src', 'spec-viewer', 'markdown', 'index.ts')],
    bundle: true,
    absWorkingDir,
    format: 'esm',
    platform: 'neutral',
    target: 'es2022',
    plugins: [stubSignals],
    outfile: join(here, 'vendor', 'viewer-markdown.mjs'),
    banner: { js: '// Generated by build.mjs from apps/vscode/webview/src/spec-viewer/markdown. Do not edit.' },
    logLevel: 'warning',
});

// The prompt preamble VS Code sends with every command (seed record, lifecycle rules). Pure strings, no host imports.
await build({
    entryPoints: [join(webview, '..', 'src', 'ai-providers', 'promptPreamble.ts')],
    bundle: true,
    absWorkingDir,
    format: 'esm',
    platform: 'neutral',
    target: 'es2022',
    outfile: join(here, 'vendor', 'preamble.mjs'),
    banner: { js: '// Generated by build.mjs from apps/vscode/src/ai-providers/promptPreamble.ts. Do not edit.' },
    logLevel: 'warning',
});

// The step timing the viewer's Overview shows and its duration format, so the board measures and prints phases the same way.
await build({
    stdin: {
        contents: [
            "export { deriveStepHistory, deriveTimingSummary } from './apps/vscode/src/features/specs/stepHistoryDerivation';",
            "export { formatElapsed } from './apps/vscode/webview/src/spec-viewer/relativeTime';",
        ].join('\n'),
        resolveDir: absWorkingDir,
        loader: 'ts',
    },
    bundle: true,
    absWorkingDir,
    format: 'esm',
    platform: 'neutral',
    target: 'es2022',
    outfile: join(here, 'vendor', 'step-history.mjs'),
    banner: { js: '// Generated by build.mjs from apps/vscode/src/features/specs/stepHistoryDerivation.ts and apps/vscode/webview/src/spec-viewer/relativeTime.ts. Do not edit.' },
    logLevel: 'warning',
});

await build({
    entryPoints: [join(webview, 'styles', 'spec-viewer', 'index.css')],
    bundle: true,
    absWorkingDir,
    outfile: join(here, 'vendor', 'viewer.css'),
    loader: { '.svg': 'dataurl', '.png': 'dataurl', '.woff2': 'dataurl' },
    banner: { css: '/* Generated by build.mjs from apps/vscode/webview/styles/spec-viewer. Do not edit. */' },
    logLevel: 'warning',
});

console.log('built vendor/viewer-markdown.mjs, vendor/preamble.mjs, vendor/step-history.mjs and vendor/viewer.css');
