// Bundles the VS Code spec viewer's markdown renderer and stylesheet into vendor/, so the board
// renders spec, plan and tasks exactly the way the extension does. Run: node apps/copilot-canvas/build.mjs

import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const here = fileURLToPath(new URL('.', import.meta.url));
const webview = join(here, '..', 'vscode', 'webview');

// The renderer's only webview dependency is a Preact signal it reads for living-spec coverage; the board has none.
const stubSignals = {
    name: 'stub-signals',
    setup(api) {
        api.onResolve({ filter: /^\.\.\/signals$/ }, () => ({ path: 'signals-stub', namespace: 'stub' }));
        api.onLoad({ filter: /.*/, namespace: 'stub' }, () => ({ contents: 'export const navState = { value: null };', loader: 'js' }));
    },
};

await build({
    entryPoints: [join(webview, 'src', 'spec-viewer', 'markdown', 'index.ts')],
    bundle: true,
    format: 'esm',
    platform: 'neutral',
    target: 'es2022',
    plugins: [stubSignals],
    outfile: join(here, 'vendor', 'viewer-markdown.mjs'),
    banner: { js: '// Generated by build.mjs from apps/vscode/webview/src/spec-viewer/markdown. Do not edit.' },
    logLevel: 'warning',
});

await build({
    entryPoints: [join(webview, 'styles', 'spec-viewer', 'index.css')],
    bundle: true,
    outfile: join(here, 'vendor', 'viewer.css'),
    loader: { '.svg': 'dataurl', '.png': 'dataurl', '.woff2': 'dataurl' },
    banner: { css: '/* Generated by build.mjs from apps/vscode/webview/styles/spec-viewer. Do not edit. */' },
    logLevel: 'warning',
});

console.log('built vendor/viewer-markdown.mjs and vendor/viewer.css');
