export const TreeContext = {
    STEERING_LOADING: 'steering-loading',
    STEERING_HEADER: 'steering-header',
    STEERING_DOCUMENT: 'steering-document',
    STEERING_FILE: 'steering-file',
    SPECKIT_HEADER: 'speckit-header',
    SPECKIT_CONSTITUTION: 'speckit-constitution',
    SPECKIT_SCRIPTS_CATEGORY: 'speckit-scripts-category',
    SPECKIT_SCRIPT: 'speckit-script',
    SPECKIT_TEMPLATES_CATEGORY: 'speckit-templates-category',
    SPECKIT_TEMPLATE: 'speckit-template',
    PROVIDER_HEADER: 'provider-header',
    PROVIDER_PROJECT_GROUP: 'provider-project-group',
    PROVIDER_USER_GROUP: 'provider-user-group',
    PROVIDER_AGENTS_GROUP: 'provider-agents-group',
    PROVIDER_SKILLS_GROUP: 'provider-skills-group',
    PROVIDER_SETTINGS: 'provider-settings',
    AGENT: 'agent',
    SKILL: 'skill',
    SKILL_WARNING: 'skill-warning',
    CREATE_GLOBAL: 'create-global-claude',
    CREATE_PROJECT: 'create-project-claude',
    SEPARATOR: 'separator',
} as const;
